
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "siva"
