name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        shell: bash
        run: |
          echo "build"
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "siva"
